### PR TITLE
Refer to objects by reference instead of accessor

### PR DESCRIPTION
**Pull request by jpalider**
On some processors and compilers (i5-2500, gcc 5.4.0 here) this change
produces smaller binary and ca. 23% speed up (20 samples for each case).

### CODE REVIEW

**Comment by krizhanovsky** [comment]
@jpalider thank you for the pull request. It's good to merge, but I'm wondering why a compiler doesn't do the optimization? Do you see the improvement with recent GCC?

**Comment by jpalider** [comment]
Hi,
thank you for merging! As for your question - not yet, this is my plan for the nearest free time slot.
My initial tests were just for fun, and I am really surprised to see this difference - especially in terms of size. I tried gprof to see if there is something obvious but did not find anything special. I tried to compare .s files but the overwhelming difference between the original version and mine put me off. I have just some wild guesses what could happen but I'd rather not share them until find some evidence :-)

**Comment by jpalider** [comment]
I have just run the tests again, on a different machine :-)
$ gcc --version
gcc (Ubuntu 7.3.0-21ubuntu1~16.04) 7.3.0
$ ls -l master orig 
-rwxr-xr-x 1 jpa jpa 34008 Sep 11 15:41 master
-rwxr-xr-x 1 jpa jpa 33912 Sep 11 15:41 orig

The system is under moderate workload (load average: 0,18, 0,23, 0,43) but the results seem to hold:
$ ./master 
8456ms
check X data...
Passed
$ ./orig 
10232ms
check X data...
Passed
where master is current HEAD and orig is HEAD~1

**Comment by krizhanovsky** [comment]
Interesting... Did you compare generated assembly? Did you use -O2 and did you try -O3?

**Comment by jpalider** [comment]
I am using the build command from lockfree_rb_q.cc file itself. O3 seems to make slight difference (just a few samples) but the ratio is roughly the same. Best if you could give a try yourself, then maybe we could clarify one thing: either I am missing something or the compiler is ;-)
As I already wrote - yes, I did generate .s files and tried to compare then, but the diff it huge.

**Comment by krizhanovsky** [comment]
Ok, I tried to run the optimized benchmark and it really gives not so bad performance improvement. `objdump` for `push()` says that `thr_pos()` is inlined in both the cases, however the function body accesses several memory locations and uses segment register (`%fs` in my case for optimized and original versions) for per-thread variable and the optimized version does all the accesses at begin of the method, so the per-thread dereferencing isn't performed on each loop iteration. This is different from the original version which does full dereferencing of the thread-local variable.

**Pull request merged**
